// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "gitlab.com/Sh00ty/dormitory_room_bot/internal/entities"

	mock "github.com/stretchr/testify/mock"

	testing "testing"

	value_objects "gitlab.com/Sh00ty/dormitory_room_bot/internal/value_objects"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: ctx, channelID, listID, item
func (_m *Repository) AddItem(ctx context.Context, channelID value_objects.ChannelID, listID value_objects.ListID, item entities.Item) error {
	ret := _m.Called(ctx, channelID, listID, item)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, value_objects.ChannelID, value_objects.ListID, entities.Item) error); ok {
		r0 = rf(ctx, channelID, listID, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateList provides a mock function with given fields: ctx, channelID, list
func (_m *Repository) CreateList(ctx context.Context, channelID value_objects.ChannelID, list entities.List) error {
	ret := _m.Called(ctx, channelID, list)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, value_objects.ChannelID, entities.List) error); ok {
		r0 = rf(ctx, channelID, list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteItem provides a mock function with given fields: ctx, channelID, listID, index
func (_m *Repository) DeleteItem(ctx context.Context, channelID value_objects.ChannelID, listID value_objects.ListID, index uint) error {
	ret := _m.Called(ctx, channelID, listID, index)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, value_objects.ChannelID, value_objects.ListID, uint) error); ok {
		r0 = rf(ctx, channelID, listID, index)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteList provides a mock function with given fields: ctx, channelID, listID
func (_m *Repository) DeleteList(ctx context.Context, channelID value_objects.ChannelID, listID value_objects.ListID) error {
	ret := _m.Called(ctx, channelID, listID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, value_objects.ChannelID, value_objects.ListID) error); ok {
		r0 = rf(ctx, channelID, listID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, channelID
func (_m *Repository) GetAll(ctx context.Context, channelID value_objects.ChannelID) ([]entities.List, error) {
	ret := _m.Called(ctx, channelID)

	var r0 []entities.List
	if rf, ok := ret.Get(0).(func(context.Context, value_objects.ChannelID) []entities.List); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.List)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, value_objects.ChannelID) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, channelID, listID
func (_m *Repository) GetList(ctx context.Context, channelID value_objects.ChannelID, listID value_objects.ListID) (entities.List, error) {
	ret := _m.Called(ctx, channelID, listID)

	var r0 entities.List
	if rf, ok := ret.Get(0).(func(context.Context, value_objects.ChannelID, value_objects.ListID) entities.List); ok {
		r0 = rf(ctx, channelID, listID)
	} else {
		r0 = ret.Get(0).(entities.List)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, value_objects.ChannelID, value_objects.ListID) error); ok {
		r1 = rf(ctx, channelID, listID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t testing.TB) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
