global:
  scrape_interval:     15s
  evaluation_interval: 15s

# поменять хосты если не на одной машине
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: dormitory_room_bot
    static_configs:
      - targets: ['localhost:9000']